theme: jekyll-theme-minimal
title: Exploring the Evolution of Female Characters in Cinema Across Different Eras.
description: Project for ADA class with the CMU Movie Summary Corpus.
show_downloads: True
navigation:
  - title: Exploring the Evolution of Female Characters in Cinema Across Different Eras.
    url: Exploring the Evolution of Female Characters in Cinema Across Different Eras.
  - title: Example
    url: example
